{% set name = "mesa-geo" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Mesa-Geo-{{ version }}.tar.gz
  sha256: 7eaff92c778438e5c09fbe12535506f8bfb44bd1f0fbda1dc5c60ebef7b79250

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - mesa >=1.1.0,<1.2.dev0
    - pip
  run:
    - python >=3.8
    - mesa >=1.1.0,<1.2.dev0
    - geopandas
    - libpysal
    - rtree
    - rasterio >=1.3b1
    - shapely
    - numpy
    - pyproj
    - folium
    - xyzservices >=2022.9.0

test:
  imports:
    - mesa_geo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/projectmesa/mesa-geo
  summary: GIS extension for the Mesa agent-based modeling framework in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamamer20
